using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public partial class GameBootstrap : MonoBehaviour
{
    private const int GridWidth = 100;
    private const int GridHeight = 100;
    private const int WaterRiverWidth = 4;
    private const float CellSize = 1f;
    private const float RoadHeight = 0.12f;
    private const float TruckCruiseSpeed = 2.65f;
    private const int TruckCargoCapacity = 5;
    private const int ForestMaxLogsStorage = 10;
    private const int FurnitureFactoryMaxBoardsStorage = 6;
    private const int FurnitureFactoryMaxTextileStorage = 6;
    private const int FurnitureFactoryMaxFurnitureStorage = 6;
    private const int DocksResourceCapacity = 8;
    private const int DocksShipTradeBatch = 3;
    private const float DocksShipIntervalMin = DayNightCycleDuration / 24f * 8f;
    private const float DocksShipIntervalMax = DayNightCycleDuration / 24f * 14f;
    private const float DocksShipDwellDuration = DayNightCycleDuration / 24f * 1.5f;
    private const float DocksShipCruiseSpeed = 2.35f;
    private const float DocksShipSpawnX = -4.5f;
    private const float DocksShipExitX = GridWidth + 4.5f;
    private const float FurnitureFactoryProcessingDuration = 5.5f;
    private const int ProductionMaxWorkersPerBuilding = 2;
    private const int WarehouseMaxWorkers        = 2;
    private const int ServiceMaxWorkersPerBuilding = 2;
    private const int AssignableBuildingWorkerSlotCapacity = 32;
    private const float ForestLogProgressPerChop = 0.08f;
    private const float CameraPanSpeed = 9f;
    private const float CameraDragPanMultiplier = 0.035f;
    private const float CameraZoomSpeed = 8f;
    private const float CameraMinHeight = 2.2f;
    private const float CameraMaxHeight = 120f;
    private const float CameraMinDistance = 5.2f;
    private const float CameraMaxDistance = 120f;
    private const float EdgeHighwayBusSpeed = 3.45f;
    private const float EdgeHighwayBusSpawnIntervalMin = 14f;
    private const float EdgeHighwayBusSpawnIntervalMax = 30f;
    private const float EdgeHighwayBusSpawnSpacing = 5.5f;
    private const float EdgeHighwayBusLaneOffset = 0.32f;
    private const float RoadLaneOffset = 0.22f;
    private const float EdgeHighwayBusLift = 0.24f;
    private const float EdgeHighwayBusPassbyDistance = 5.5f;
    private const float LocalBusStopDwellGameMinutes = 5f;
    private const float LocalBusSpeedMultiplier = 1.12f;
    private const int LocalBusMaxPassengers = 5;
    private const int LocalBusFare = 1;
    private const float HiringBusStopDuration = 2.8f;
    private const float TruckFollowDistance = 4.4f;
    private const float TruckFollowHeight = 2.05f;
    private const float TruckFollowLookHeight = 1.05f;
    private const float TruckSegmentStartLift = RoadHeight + 0.32f;
    private const float LocalBusRoadSurfaceLift = RoadHeight + 0.30f;
    private const float TruckSuspensionBobAmount = 0.045f;
    private const float TruckWheelRadius = 0.12f;
    private const float TruckCargoInteractionDuration = 3f;
    private const float TruckFuelCapacity = 100f;
    private const float TruckFuelPerCell = 0.5f;
    internal const float TruckAutoRefuelThreshold = 50f;
    private const float WaterEffectsUpdateInterval = 1f / 24f;
    private const float WaterEffectsFarUpdateInterval = 1f / 10f;
    private const float WaterLodMediumCameraHeight = 18f;
    private const float WaterLodFarCameraHeight = 28f;
    private const float FarZoomVisualLodEnterHeight = 46f;
    private const float FarZoomVisualLodExitHeight = 40f;
    private const float DriverSleepDuration = DayNightCycleDuration / 24f * 8f;
    private const float WorkerCanteenDuration = DayNightCycleDuration / 24f * 1f;
    private const float WorkerLeisureDuration = DayNightCycleDuration / 24f * 2f;
    private const float WorkerGamblingHallDuration = DayNightCycleDuration / 24f * 2.5f;
    private const float WorkerCityParkDuration     = DayNightCycleDuration / 24f * 1.5f;
    private const int   WorkerGamblingMinBalance   = 5;
    private const int   HousePurchasePrice         = 300;
    private const int   MaxPersonalHouseResidents  = 2;
    private const int   MaxWorkerFamilyChildren    = 2;
    private const int   WorkerFamilyNextChildReadinessThreshold = 70;
    private const float WorkerChildBirthMinHours   = 192f;
    private const float WorkerChildBirthMaxHours   = 288f;
    private const float WorkerChildBirthRetryHours = 24f;
    private const int   WorkerChildBabyStageDays   = 3;
    private const int   WorkerChildToddlerStageDays = 5;
    private const int   WorkerChildChildStageDays  = 8;
    private const int   WorkerChildTeenStageDays   = 8;
    private const float WorkerChildStayInTownChance = 0.68f;
    private const int   CarPurchasePrice           = 100;
    private const float PersonalCarSpeed           = 4.55f;
    private const int   WorkerGamblingMinBet       = 5;
    private const int   WorkerGamblingMaxBet       = 10;
    private const float WorkerFreeIdleMinDuration = DayNightCycleDuration / 24f * 1f;
    private const float WorkerFreeIdleMaxDuration = DayNightCycleDuration / 24f * 3f;
    private const float LaborExchangePostingInterval = DayNightCycleDuration / 24f * 1.5f;
    private const float LaborExchangeInterviewDuration = DayNightCycleDuration / 24f * 0.35f;
    private const int LaborExchangeMaxActivePostings = 6;
    private const float DriverWalkSpeed = 2.2f;
    private const float DriverIdleWanderSpeed = 1.35f;
    private const float FootpathWearPerCellVisit = 0.35f;
    private const float FootpathVisibleWear = 8f;
    private const float FootpathEstablishedWear = 22f;
    private const float FootpathStrongWear = 48f;
    private const float FootpathMaxWear = 64f;
    private const float FootpathFreshWalkCost = 0.82f;
    private const float FootpathStrongWalkCost = 0.58f;
    private const float DriverWalkOccupiedCellCost = 1.1f;
    private const float DriverWalkAdjacentCellCost = 0.18f;
    private const float DriverWalkMaxCongestionCost = 2.2f;
    private const float DriverIdleWanderPauseMin = 2.2f;
    private const float DriverIdleWanderPauseMax = 4.6f;
    private const float DriverIdlePersonalSpace = 0.62f;
    private const float DriverIdleConversationDistance = 2.1f;
    private const float DriverIdleConversationDurationMin = 3.4f;
    private const float DriverIdleConversationDurationMax = 6.2f;
    private const float DriverIdleConversationCooldownMin = 4.5f;
    private const float DriverIdleConversationCooldownMax = 8.5f;
    private const float DriverIdleConversationStartChance = 0.42f;
    private const int SmokingParticlePoolSize = 5;
    private const float SmokingParticleEmitInterval = 1.1f;
    private const float SmokingParticleMaxLife = 3.2f;
    private const int AmbientAirGlobalParticleCount = 34;
    private const int AmbientAirForestParticleCount = 18;
    private const int AmbientAirHighwayDustParticleCount = 20;
    private const int MiscBirdCount = 10;
    private const int AmbientCatCount = 3;
    private const int AmbientSquirrelCount = 22;
    private const int NightStarCount = 120;
    private const int AmbientBeeCount = 8;
    private const int AmbientLanternMothSwarmMaxCount = 8;
    private const int AmbientFireflyCount = 25;
    private const int AmbientFallingLeafCount = 30;
    private const int AmbientFrogCount = 5;
    private const int RainDropCount = 280;
    private const int RiverFishMaxActiveCount = 6;
    private const int LakeFishMaxCount = 5;
    private const int ExhaustSmokePoolSize = 36;
    private const int TruckDirtDustPoolSize = 28;
    private const float ExhaustEmitInterval = 0.28f;
    private const float TruckDirtDustEmitInterval = 0.13f;
    private const float BuildingSmokeEmitInterval = 0.38f;
    private const int StartingTreasury = 5000;
    private const int DefaultDailyBuildingTaxPercent = 10;
    private const int MinDailyBuildingTaxPercent = 0;
    private const int MaxDailyBuildingTaxPercent = 50;
    private const float MoneyPopupDuration = 1.4f;
    private const int AudioSampleRate = 22050;
    private const int MaxTruckCount = 5;
    private const int MaxBusCount = 3;
    private const int HireDriverCost = 50;
    private const int WorkerStartingMoneyMin = 50;
    private const int WorkerStartingMoneyMax = 100;
    private const int MotelBootstrapWorkerWaveCount = 10;
    private const int TutorialHireWorkerWaveCount = MotelBootstrapWorkerWaveCount;
    private const int DebugHireWorkerWaveCount = 10;
    private const float HiringBusDisembarkInterval = 0.22f;
    private const int TutorialWarehouseLoaderGoalCount = 3;
    private const int TutorialLocalBusStopGoalCount = 2;
    private const int TutorialBusDriverGoalCount = 3;
    private const int InitialWorkerCount = 3;
    private const int MaxMoneyLedgerEntries = 128;
    private const float DayNightCycleDuration = 440f; // 4 periods × 110s = 7m20s full day
    private const float DriverShiftArrivalLeadHours = 1f;
    private const int ProductionWorkStartHour = 8;
    private const int ProductionWorkEndHour = 18;
    private const float DioramaCameraMinPitch = 8f;
    private const float DioramaCameraPitch = 52f;
    private static readonly Vector3 DioramaCameraOffset = new(-24f, 30f, -24f);
    private static readonly Vector3 CloudTravelDir = new Vector3(1f, 0f, 0.4f).normalized;
    private const float CloudTravelLength = 260f; // Full cloud path from off-map spawn to exit.

    private readonly HashSet<Vector2Int> waterCells = new();
    private readonly HashSet<Vector2Int> lakeWaterCells = new();
    private readonly HashSet<Vector2Int> naturalBeachCells = new();
    private readonly HashSet<Vector2Int> roadCells = new();
    private readonly HashSet<Vector2Int> edgeHighwayCells = new();
    private readonly HashSet<Vector2Int> roadConstructionHiddenCells = new();
    private readonly HashSet<Vector2Int> miscOccupiedCells = new();
    private readonly Dictionary<Vector2Int, float> footpathWearByCell = new();
    private readonly HashSet<Vector2Int> visibleFootpathCells = new();
    private readonly Dictionary<Vector2Int, GameObject> roadVisuals = new();
    private readonly Dictionary<LocationType, LocationData> locations = new();
    private readonly List<LocationData> extraServiceLocations = new();
    private readonly List<Vector2Int> activePath = new();
    private readonly List<Transform> truckWheels = new();
    private readonly List<Transform> truckFrontWheels = new();
    private readonly List<Light> truckHeadlights = new();
    private readonly List<Light> locationNightLights = new();
    private readonly List<Renderer> locationNightLightRenderers = new();
    private readonly List<Material> locationNightLightMaterials = new();
    private readonly List<int> locationNightLightMaterialOwnerInstanceIds = new();
    private readonly List<int> locationNightLightOwnerInstanceIds = new();
    private readonly List<Color> locationNightLightOffColors = new();
    private readonly List<Color> locationNightLightOnColors = new();
    private readonly List<float> locationNightLightMaxIntensities = new();
    private readonly List<float> locationNightLightRanges = new();
    private readonly List<Color> locationNightPointLightOnColors = new();
    private readonly List<float> locationNightPointLightMaxIntensities = new();
    private readonly List<float> locationNightPointLightRanges = new();
    private readonly List<Vector3> locationTrashCanMealTargets = new();
    private readonly List<RoadLanternData> roadLanterns = new();
    private readonly CellLightData[,] cellLighting = new CellLightData[GridWidth, GridHeight];
    private bool isCellLightingDirty = true;
    private float lastCellLightingNightStrength = -1f;
    private readonly Dictionary<Vector2Int, (GameObject Root, RoadLanternData Data)> roadCellLanternMap = new();
    private readonly Dictionary<Vector2Int, (GameObject Root, Vector2Int SideCell)> roadCellBenchMap = new();
    private readonly HashSet<Vector2Int> benchSideCells = new();
    private readonly Dictionary<Vector2Int, (GameObject Root, Vector2Int SideCell)> roadCellSignMap = new();
    private readonly HashSet<Vector2Int> signSideCells = new();
    private readonly List<TruckAgent> truckAgents = new();
    private readonly List<BusAgent> busAgents = new();
    private readonly List<DriverAgent> driverAgents = new();
    private readonly List<WorkerFamily> workerFamilies = new();
    private readonly List<WorkerFamilyPendingFormation> pendingWorkerFamilyFormations = new();
    private readonly List<WorkerChild> workerChildren = new();
    private readonly List<LaborExchangePosting> laborExchangePostings = new();
    private readonly List<ForestWorkerAmbient> forestWorkers = new();
    private readonly List<Vector3> forestWorkPoints = new();
    private readonly List<Transform> forestWorkTargetTrees = new();
    private readonly List<ForestTreeWobble> forestTreeWobbles = new();
    private readonly List<MiscTreeSway> miscTreeSways = new();
    private readonly List<Vector3> miscTreePerchPoints = new();
    private GameObject[] importedMiscTreePrefabs;
    private bool hasLoadedImportedMiscTreePrefabs;
    private readonly List<MiscBirdData> miscBirds = new();
    private readonly List<Vector3> ambientCatRoamPoints = new();
    private readonly List<AmbientCatData> ambientCats = new();
    private readonly List<Vector3> ambientSquirrelRoamPoints = new();
    private readonly List<float> ambientSquirrelPerchHeights = new();
    private readonly List<AmbientSquirrelData> ambientSquirrels = new();
    private readonly List<NightStarData> nightStars = new();
    private readonly List<Vector3> flowerBeePoints = new();
    private readonly List<AmbientBeeData> ambientBees = new();
    private readonly List<AmbientLanternMothSwarmData> ambientLanternMothSwarms = new();
    private readonly List<AmbientFireflyData> ambientFireflies = new();
    private readonly List<AmbientFallingLeafData> ambientFallingLeaves = new();
    private readonly List<AmbientFrogData> ambientFrogs = new();
    private readonly List<Vector2Int> ambientFrogRoamCells = new();
    private readonly List<WaterSurfaceTileData> waterSurfaceTiles = new();
    private readonly List<WaterBodyTileData> waterBodyTiles = new();
    private readonly List<WaterShoreFoamData> waterShoreFoams = new();
    private readonly List<WaterShoreWashPatchData> waterShoreWashPatches = new();
    private readonly List<RiverFishData> riverFish = new();
    private readonly List<LakeFishData> lakeFish = new();
    private readonly List<List<Vector2Int>> perLakeWaterCells = new();
    private readonly List<DistantCloudData> distantClouds = new();
    private readonly List<AmbientAirParticleData> ambientAirParticles = new();
    private readonly List<ShadowLodRendererData> shadowLodRenderers = new();
    private readonly List<MoneyLedgerEntry> moneyLedgerEntries = new();
    private readonly List<TaxPolicy> taxPolicies = new();
    private readonly HashSet<LocationType> occupiedServiceLocations = new();
    private readonly Dictionary<LocationType, GameObject> locationSelectionHighlights = new();
    private readonly List<GameObject> localStopSelectionHighlights = new();
    private readonly List<LocationData> personalHouses = new();
    private readonly List<GameObject> personalHouseSelectionHighlights = new();
    private int selectedPersonalHouseIndex = -1;
    private readonly List<EdgeHighwayBusData> edgeHighwayBuses = new();
    private readonly List<RiverBoatData> riverBoats = new();
    private LocalBusRouteData localBusRoute;
    private float[,] terrainHeights = new float[GridWidth, GridHeight];
    private readonly List<NaturalZoneData> forestZones = new();
    private readonly List<NaturalZoneData> hillZones = new();
    private readonly List<NaturalZoneData> lakeZones = new();
    private int nextWorkerFamilyId = 1;
    private int nextWorkerChildId = 1;
    private int nextLaborExchangePostingId = 1;
    private int nextLocationInstanceId = 1;
    private int nextTaxPolicyId = 1;
    private float laborExchangePostingTimer;
    private int laborExchangeApplicantsToday;
    private int laborExchangeApplicantDay = -1;
    private bool wasLaborExchangeBuiltLastTick;
    private bool wasLaborExchangeStaffedLastTick;

    private Camera mainCamera;
    private GameObject truckObject;
    private Transform truckVisualRoot;
    private Transform truckBodyTransform;
    private Transform truckCabinTransform;
    private Renderer truckHeadlightLeftRenderer;
    private Renderer truckHeadlightRightRenderer;
    private Material truckHeadlightLeftMaterial;
    private Material truckHeadlightRightMaterial;
    private Transform worldRoot;
    private Transform groundRoot;
    private Transform gridLinesRoot;
    private Material gridLinesMaterial;
    private bool isGridBuildModeVisualActive;
    private Transform roadsRoot;
    private Transform unifiedRoadVisualRoot;
    private Transform roadConstructionWaveRoot;
    private Coroutine roadConstructionWaveCoroutine;
    private bool suppressUnifiedRoadVisualRebuild;
    private bool suppressRoadsideRefresh;
    private readonly HashSet<Vector2Int> pendingRoadsideRefreshCells = new();
    private Transform lanternsRoot;
    private Transform roadsidePropsRoot;
    private Transform roadsideSignsRoot;
    private readonly List<Vector3> roadsideBenchPositions = new();
    private readonly bool[] benchOccupied = new bool[GridWidth * GridHeight / 16];
    private readonly List<Vector3> cityParkBenchPositions = new();
    private readonly bool[] cityParkBenchOccupied = new bool[8];
    private Transform miscRoot;
    private Transform ambientAirRoot;
    private Transform exhaustSmokeRoot;
    private Transform truckDirtDustRoot;
    private readonly List<ExhaustSmokeParticle> exhaustSmokePool = new();
    private readonly List<ExhaustSmokeParticle> truckDirtDustPool = new();
    private float localBusExhaustEmitTimer;
    private float sawmillSmokeEmitTimer;
    private float furnitureFactorySmokeEmitTimer;
    private Transform miscBirdRoot;
    private Transform ambientCatRoot;
    private Transform ambientSquirrelRoot;
    private Transform nightSkyRoot;
    private Material moonMaterial;
    private Transform ambientBeeRoot;
    private Transform ambientLanternMothRoot;
    private Transform ambientFireflyRoot;
    private Transform ambientFallingLeafRoot;
    private Transform ambientFrogRoot;
    private Transform waterEffectsRoot;
    private Transform riverFishRoot;
    private Transform lakeFishRoot;
    private bool isFarZoomVisualLodActive;
    private AudioSource uiAudioSource;
    private AudioSource truckLoopAudioSource;
    private AudioSource cityMusicSource;      // looping main theme for city mode
    private AudioSource mainMenuMusicSource;  // looping music for main menu / pause screen
    private AudioSource natureCicadasAudioSource;
    private AudioSource natureForestBirdsAudioSource;
    private AudioSource natureNightAudioSource;
    private AudioSource natureRainCalmAudioSource;
    private AudioSource natureRainStrongAudioSource;
    private AudioSource natureRiverAudioSource;
    private AudioSource natureWindCalmAudioSource;
    private AudioSource natureWindForestAudioSource;
    private Material groundSurfaceMaterial;
    private Material grassSurfaceMaterial;
    private Material waterShallowMaterial;
    private Material waterDeepMaterial;
    private Material beachSurfaceMaterial;
    private Material shoreSurfaceMaterial;
    private Material roadSurfaceMaterial;
    private Material roadShoulderMaterial;
    private Material highwaySurfaceMaterial;
    private Material highwayShoulderMaterial;
    private Texture2D groundSurfaceTexture;
    private Texture2D grassSurfaceTexture;
    private Texture2D forestSurfaceTexture;
    private Texture2D beachSurfaceTexture;
    private Texture2D footpathSurfaceTexture;
    private Texture2D constructionMudSurfaceTexture;
    private Texture2D roadSurfaceTexture;
    private Texture2D roadShoulderSurfaceTexture;
    private Texture2D highwaySurfaceTexture;
    private Texture2D riverSurfaceTexture;
    private Texture2D riverDeepTexture;
    private Texture2D riverRippleTexture;
    private Texture2D riverFoamTexture;
    private Texture2D lakeSurfaceTexture;
    private Texture2D lakeDeepTexture;
    private Texture2D lakeRippleTexture;
    private Light mainDirectionalLight;
    private Volume dioramaVolume;
    private VolumeProfile dioramaVolumeProfile;
    private ColorAdjustments dioramaColorAdjustments;
    private Bloom dioramaBloom;
    private DepthOfField dioramaDepthOfField;
    private Vignette dioramaVignette;
    private FilmGrain                   dioramaFilmGrain;
    private ShadowsMidtonesHighlights   dioramaSMH;
    private ChromaticAberration         dioramaChromaticAberration;
    private bool  gfxFilmGrainEnabled    = true;
    private bool  gfxSmhEnabled          = true;
    private bool  gfxChromAberrEnabled   = true;
    private bool  gfxDepthOfFieldEnabled = true;
    private float gfxBloomIntensity      = 0.55f;
    private float gfxBloomReach          = 0.55f;
    private float gfxSaturation          = 0.55f;
    private float gfxContrast            = 0.60f;
    private float gfxWarmth              = 0.55f;
    private float gfxVignette            = 0.45f;
    private float gfxDepthOfFieldAmount  = 0.55f;
    private float gfxFilmGrainIntensity  = 0.35f;
    private float gfxChromAberrIntensity = 0.35f;
    private GameObject selectedLocationLabelRoot;
    private TextMesh selectedLocationLabelText;
    private readonly List<TextMesh> selectedLocationLabelOutlines = new();
    private GameObject selectedEntityHighlight;
    private GameObject cargoTransferCrate;
    private GameObject buildHoverHighlight;
    private GameObject buildHoverDrivewayHighlight;
    private GameObject buildCursorAssistRoot;
    private Light buildCursorAssistLight;
    private readonly List<GameObject> buildHoverCellHighlights = new();
    private readonly List<Vector2Int> buildPreviewFootprintCells = new();
    private readonly List<Vector2Int> buildPreviewWalkBufferCells = new();
    private readonly List<Vector2Int> buildPreviewRoadDirections = new();
    private Vector2Int? buildPreviewDrivewayCell;
    private Vector2Int? roadPathStart;
    private GameObject roadPathStartHighlight;
    private GameObject roadPathStartSideHighlight;
    private int buildPlacementRotationIndex;
    private GameObject selectedDebugCellHighlight;
    private GameObject selectedDebugCellOutline;
    private Transform edgeHighwayBusRoot;
    private Vector2Int truckCell;
    private Vector3 truckTargetWorld;
    private Vector3 truckSegmentStartWorld;
    private Vector3 truckSmoothedForward = Vector3.forward;
    private bool isTruckMoving;
    private bool isTruckInteracting;
    private bool isTruckWaitingForService;
    private TruckAgent currentLoadedTruckAgent;
    private bool isDriverRescueActive;
    private CargoType truckCargoType = CargoType.None;
    private int truckCargoAmount;
    private float productionTimer;
    private Vector3 cameraFocusPoint;
    private Vector3 cameraOffset;
    private Vector3 cameraTargetOffset;
    private Vector2 lastMousePosition;
    private Vector2 lastMiddleMousePosition;
    private Vector2 rightMousePressPosition;
    private float truckSegmentProgress;
    private float truckSegmentDuration;
    private float truckWheelSpinAngle;
    private float truckSteerAngle;
    private float truckInteractionTimer;
    private float moneyPopupTimer;
    private float nextMissingWarehouseFeedTime;
    private float truckFuel = TruckFuelCapacity;
    private float dayNightCycleTimer = DayNightCycleDuration * 0.25f; // start at 06:00 - morning
    private int   currentDay = 1;
    private int   dailyBuildingTaxPercent = DefaultDailyBuildingTaxPercent;
    private int   lastTaxCollectionDay;
    private int   lastTaxCollectedAmount;
    private int   lastTaxedBuildingCount;
    private int   taxStatsDay;
    private int   taxCollectedToday;
    private int   taxEventsToday;
    private int   taxCollectedPreviousDay;
    private int   taxEventsPreviousDay;
    private float currentStylizedDaylight = 1f;
    private float forestProductionProgress;
    private float sawmillProcessingTimer;
    private float furnitureFactoryProcessingTimer;
    private float terrainNoiseOffsetX;
    private float terrainNoiseOffsetY;
    private LocationType? selectedLocation;
    private int selectedLocalStopIndex = -1;
    private bool isTruckDetailsOpen;
    private bool isLocalBusDetailsOpen;
    private bool isRightMouseDragging;
    private bool isCameraReturningToDiorama;
    private bool isCameraRotatingToTarget;
    private bool isTruckCameraFocused;
    private bool isTruckAutoModeEnabled;
    private bool isFleetScreenDirty = true;
    private bool isMainMenuOpen = true;
    private bool isRacingActive;
    private int racingBonusEarned;
    private int selectedTruckNumber = 1;
    private int money;
    private readonly TradeState tradeState = new();
    private readonly TradeSimulation tradeSimulation = new();
    private int cottonStored { get => tradeState.CottonStored; set => tradeState.CottonStored = value; }
    private int textileStored { get => tradeState.TextileStored; set => tradeState.TextileStored = value; }
    private int furnitureStored { get => tradeState.FurnitureStored; set => tradeState.FurnitureStored = value; }
    private int currentAssignedTripReward;
    private bool isFleetPanelOpen;
    private bool isShiftsPanelOpen;
    private bool isDriversPanelOpen;
    private int selectedShiftDriverId; // DriverId, 0 = none
    private int intercityDriverId;
    private readonly int[] busDriverShiftIds = new int[3];
    public enum TradePolicyMode
    {
        None,
        SellAbove,
        BuyUpTo
    }

    private TradeResourceType selectedTradeResourceType { get => tradeState.SelectedResourceType; set => tradeState.SelectedResourceType = value; }
    private TradeOrderType selectedTradeOrderType { get => tradeState.SelectedOrderType; set => tradeState.SelectedOrderType = value; }
    private int selectedTradeOrderAmount { get => tradeState.SelectedOrderAmount; set => tradeState.SelectedOrderAmount = value; }
    private bool isTradeResourceDropdownOpen;
    private bool isTradeActionDropdownOpen;
    private int nextTradeOrderId { get => tradeState.NextOrderId; set => tradeState.NextOrderId = value; }

    public sealed class TradeHudOrder
    {
        public int Id;
        public TradeResourceType ResourceType;
        public TradeOrderType OrderType;
        public int Amount;
        public int TargetRegionIndex = -1; // -1 = generic (Trade panel), 0-8 = specific region
    }

    private readonly bool[] worldMapTradeRoutesBuilt = new bool[9];

    private List<TradeHudOrder> activeTradeHudOrders => tradeState.ActiveHudOrders;
    private TradePolicyMode[] tradePolicyModes => tradeState.PolicyModes;
    private int[] tradePolicyTargets => tradeState.PolicyTargets;

    private string tradeDispatchStatusText = "Assign a Truck Driver shift to unlock trade dispatch.";
    private bool isResourcesPanelOpen;
    private bool isEconomyPanelOpen;
    private bool isEconomyTaxesTabActive = true;
    private bool isTradePanelOpen;
    private bool isTradeScreenDirty = true;
    private bool isBuildPanelOpen;
    private bool isWorldMapPanelOpen;
    private bool isWorldMapSimulationPauseActive;
    private int worldMapPauseRestoreSpeed = 1;
    private bool isStatesPanelOpen;
    private int selectedWorldMapRegionIndex = -1;
    private int moneyPopupAmount;
    private int gameSpeedMultiplier = 1;
    private int lastActiveGameSpeedMultiplier = 1;
    private int nextDriverId = 1;
    private TripType currentAssignedTrip = TripType.None;
    private BuildTool activeBuildTool = BuildTool.None;
    private HashSet<BuildTool> unlockedBuildTools;
    private bool areTutorialVacanciesFullyUnlocked;
    private bool isTutorialTruckDriverVacancyUnlocked;
    private bool hasShownLocalBusStopMinimumHint;
    private readonly List<LocationData> localStops = new();
    private Vector2Int? hoveredBuildCell;
    private Vector2Int? selectedDebugCell;
    private float edgeHighwayBusSpawnTimerCitySide;
    private float edgeHighwayBusSpawnTimerOuterSide;
    private float riverBoatSpawnTimerLeft;
    private float riverBoatSpawnTimerRight;
    private Transform riverBoatRoot;
    private HiringDriverArrivalData hiringDriverArrival;


}
